# CI 单元测试环境
UNITTEST:
  # 支持的任务类型
  service:
    - aaa
    - bbb

  # 对应任务类型需要的数据源
  source_db:
    aaa:
      # 数据源名称
      source_name: 'aaa'

      # 该数据源对应的消息队列topic的名称
      topic_name: 'si-test'

      # topic对应的消费者id
      consumer_id: 'CID_aaa_2017'

  # api任务状态查询最大数量
  max_status_task: 10

# 测试环境
TEST:
  # 支持的任务类型
  service:
    - al-sample
    - al-event-amount-analysis

  # 对应任务类型需要的数据源
  source_db:
    al-sample:
      # 数据源名称
      source_name: 'al-sample'

      # 该数据源对应的消息队列topic的名称
      topic_name: 'si-ai-test'

      # topic对应的消费者id
      consumer_id: 'CID_si-ai-test_al-sample'
    al-event-amount-analysis:
      # 数据源名称
      source_name: 'al-event-amount-analysis'

      # 该数据源对应的消息队列topic的名称
      topic_name: 'si-ai-test'

      # topic对应的消费者id
      consumer_id: 'CID_si-ai-test_al-event-amount-analysis'
  # api任务状态查询最大数量
  max_status_task: 10

# 预发布环境
STAGE:
  # 支持的任务类型
  service:
    - aaa
    - bbb

  # 对应任务类型需要的数据源
  source_db:
    aaa:
      # 数据源名称
      source_name: 'mongo'

      # 该数据源对应的消息队列topic的名称
      topic_name: 'si-test'

      # topic对应的消费者id
      consumer_id: 'CID_aaa_2017'
    bbb:
      source_name: 'mysql'
      topic_name: 'si-test'
      consumer_id: 'CID_aaa_2017'

  # api任务状态查询最大数量
  max_status_task: 10

# 正式环境
PRODUCTION:
  # 支持的任务类型
  service:
    - aaa
    - bbb

  # 对应任务类型需要的数据源
  source_db:
    aaa:
      # 数据源名称
      source_name: 'mongo'

      # 该数据源对应的消息队列topic的名称
      topic_name: 'si-test'

      # topic对应的消费者id
      consumer_id: 'CID_aaa_2017'
    bbb:
      source_name: 'mysql'
      topic_name: 'si-test'
      consumer_id: 'CID_aaa_2017'

  # api任务状态查询最大数量
  max_status_task: 10
